### ISSUE TITLE
msf_get_results() - Error: lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by stevebit** [MySportsFeeds/mysportsfeeds-r#10]
Hi,
I keep getting the following error when the run the msf_get_results function.  I'm not sure what is causing it.

full_sched <- msf_get_results(version='1.1',league='mlb',season='2016-playoff',feed='full_game_schedule')

Error
No encoding supplied: defaulting to UTF-8.
Error: lexical error: invalid char in json text.
                                       <html>  	<head>  		<title>Authe
                     (right here) ------^

**Comment by bradbarkhouse** [comment]
Have you tried a similar request over HTTP GET?  It's very likely this is the result of not being subscribed (403 response code) or a problem with your authentication (401). Please reach out to us on Slack if you're still having trouble.
