### ISSUE TITLE
Error while installing wrapper in Rstudio

### ISSUE THREAD

**Issue by Tim-Stafford** [MySportsFeeds/mysportsfeeds-r#3]
Hi, noticed an error while installing the wrapper, I believe it is because the authenticate_v1_0 was renamed to authenticate_v1_x?

Error: package or namespace load failed for ‘mysportsfeedsR’ in namespaceExport(ns, exports):
 undefined exports: authenticate_v1_0
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/mysportsfeedsR’
Installation failed: Command failed (1)

**Comment by bradbarkhouse** [comment]
Thanks for that @BobOscarHappyApple!  Just corrected for the name change.
