### ISSUE TITLE
Can't open the RStudio project file

### ISSUE THREAD

**Issue by znmeb** [MySportsFeeds/mysportsfeeds-r#4]
I get the following error when I try to open the RStudio project file `mysportsfeedsR.Rproj
`
![screenshot from 2018-08-26 21-45-50](https://user-images.githubusercontent.com/4938/44641046-eef57200-a979-11e8-9d8a-fd0408c232d1.png)

It looks like you have the *package* version in the `Version` parameter of `mysportsfeedsR.Rproj
`

```
Version: 2.0

RestoreWorkspace: No
SaveWorkspace: No
AlwaysSaveHistory: Default
```

That value needs to be the *RStudio' version, not the version of the package. I can open a pull request if you want.

**Comment by bradbarkhouse** [comment]
Pulled and fixed, thanks!
