### ISSUE TITLE
Error: parse error: premature EOF when looping

### ISSUE THREAD

**Issue by fbetteo** [MySportsFeeds/mysportsfeeds-r#8]
I'm getting the following error when looping through dates to download daily team gamelogs.

![imagen](https://user-images.githubusercontent.com/13087655/52166388-5662db00-26eb-11e9-9295-7a70cd353612.png)

Each time I execute the loop it downloads one date further. So this is the 4th time I run it in a row. If I run it again I can download 20171020 games but will crash in 20171021 and so on.

Not sure where this is coming from.

Windows 10.
R 3.5.1

**Comment by bradbarkhouse** [comment]
Sounds like you need to build in some graceful error handling.  Game logs requests need to be paced to avoid killing our servers.  If you request too many, you'll likely get a 429 response, which I suspect is what's happening here.

**Comment by fbetteo** [comment]
Strangely each iteration I download more files than the previous one,  that's why I thought it wasn't a 429. Also tried pacing the function with some sleep time but still happening. I'm going with the error handling that seems working fine enough.
Thanks!

**Comment by bradbarkhouse** [comment]
Ah, you got progressively further, probably because your previous requests had been cached (on our side).  Sounds like you're headed in the right direction now, so I'll go ahead and close this issue.
